apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: multi-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          command: ["/bin/sh", "-c", "sleep 15 && nginx -g 'daemon off;'"]
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
