apiVersion: apps/v1
kind: Deployment
metadata:
  name: capital-gains
  namespace: multi-service-app
  labels:
    app: capital-gains
spec:
  replicas: 1  # Running only one replica of the capital-gains service
  selector:
    matchLabels:
      app: capital-gains
  template:
    metadata:
      labels:
        app: capital-gains
    spec:
      containers:
        - name: capital-gains
          image: capital-gains
          imagePullPolicy: IfNotPresent  # Corrected indentation
          ports:
            - containerPort: 8080  # Port the container listens on
          env:
            - name: STOCKS_SERVICE_URL
              value: "http://stocks.multi-service-app.svc.cluster.local:8000"  # Kubernetes service URL of the stock service

