apiVersion: v1
kind: Service
metadata:
  name: capital-gains
  namespace: multi-service-app
spec:
  selector:
    app: capital-gains
  ports:
    - protocol: TCP
      port: 8080 # The port the service will expose
      targetPort: 8080 # The port the container is listening on
  type: ClusterIP # Exposes the service only within the cluster

