apiVersion: v1
kind: Service
metadata: 
  name: database
  namespace: multi-service-app
  labels:
    app: database
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: database

